apiVersion: v1
kind: ServiceAccount
metadata:
  name: infinity-gateway
  namespace: infinity-gateway
  labels:
    app: infinity-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infinity-gateway
  namespace: infinity-gateway
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infinity-gateway
  namespace: infinity-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infinity-gateway
subjects:
- kind: ServiceAccount
  name: infinity-gateway
  namespace: infinity-gateway
